# Generated by Django 3.1 on 2020-08-21 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleforteacher',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='DirectMessageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('attachment', models.ImageField(upload_to='media')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsite.studentregistration')),
                ('teacher_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsite.teacherregistration')),
            ],
        ),
    ]
