# Generated by Django 3.1 on 2020-08-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0002_teacherregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_title', models.CharField(max_length=200)),
                ('notice_description', models.TextField()),
                ('time_changed', models.DateTimeField(auto_now=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
