# Generated by Django 3.1 on 2020-08-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0002_auto_20200821_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addsubject',
            name='subject_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
