# Generated by Django 3.1 on 2020-09-02 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0002_auto_20200902_0641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherregistration',
            old_name='teacher_id',
            new_name='teacher_unique_id',
        ),
    ]
