# Generated by Django 3.1 on 2020-08-13 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0003_noticeupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherregistration',
            name='class_number',
        ),
        migrations.RemoveField(
            model_name='teacherregistration',
            name='subject_name',
        ),
        migrations.CreateModel(
            name='RoleForTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsite.addclassnumber')),
                ('subject_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsite.addsubject')),
                ('teacher_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsite.teacherregistration')),
            ],
        ),
    ]
