# Generated by Django 3.1 on 2020-08-23 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0003_auto_20200823_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addclassnumber',
            name='class_number',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='addsubject',
            name='class_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsite.addclassnumber', to_field='class_number'),
        ),
        migrations.AlterField(
            model_name='roleforteacher',
            name='class_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsite.addclassnumber', to_field='class_number'),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='class_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsite.addclassnumber', to_field='class_number'),
        ),
    ]
