# Generated by Django 3.1 on 2020-08-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0004_auto_20200813_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherregistration',
            name='password',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
