# Generated by Django 3.1 on 2020-08-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0005_teacherregistration_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherregistration',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
