# Generated by Django 3.1 on 2020-09-03 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0005_auto_20200902_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='class_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminsite.addclassnumber', to_field='class_number'),
        ),
    ]
