# Generated by Django 3.1 on 2020-08-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0006_noticeupload_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeupload',
            name='created_by',
            field=models.CharField(max_length=200),
        ),
    ]
