# Generated by Django 3.1.1 on 2020-09-12 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0006_auto_20200903_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directmessagemodel',
            old_name='student_admission_number',
            new_name='admission_number',
        ),
    ]
