# Generated by Django 3.1 on 2020-08-30 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0008_auto_20200830_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleforteacher',
            name='subject_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsite.addsubject', to_field='subject_name', unique=True),
        ),
    ]
