# Generated by Django 3.1 on 2020-09-04 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('pass_status', models.BooleanField(default=False)),
                ('class_number', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminsite.addclassnumber', to_field='class_number')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsite.studentregistration', to_field='admission_number')),
                ('subject_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsite.addsubject', to_field='subject_name')),
                ('teacher_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsite.teacherregistration', to_field='teacher_unique_id')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceUploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_held', models.IntegerField(default=0)),
                ('class_present', models.IntegerField(default=0)),
                ('class_number', models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='adminsite.addclassnumber', to_field='class_number')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsite.studentregistration', to_field='admission_number')),
                ('subject_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsite.addsubject', to_field='subject_name')),
                ('teacher_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminsite.teacherregistration', to_field='teacher_unique_id')),
            ],
        ),
    ]
