# Generated by Django 3.1 on 2020-09-02 06:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id11', to='adminsite.studentregistration')),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='adminsite.studentregistration')),
                ('subject_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='adminsite.addsubject')),
                ('teacher_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='adminsite.teacherregistration')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceUploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.BooleanField(default=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id22', to='adminsite.studentregistration')),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='adminsite.studentregistration')),
                ('subject_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='adminsite.addsubject')),
                ('teacher_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='adminsite.teacherregistration')),
            ],
        ),
    ]
