# Generated by Django 3.1 on 2020-08-30 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0007_auto_20200826_1504'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendanceuploads',
            old_name='teacher_name',
            new_name='teacher_id',
        ),
        migrations.RemoveField(
            model_name='attendanceuploads',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='attendanceuploads',
            name='date',
        ),
        migrations.RemoveField(
            model_name='attendanceuploads',
            name='student_name',
        ),
        migrations.AddField(
            model_name='attendanceuploads',
            name='class_held',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendanceuploads',
            name='class_present',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendanceuploads',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='adminsite.studentregistration'),
        ),
        migrations.AlterField(
            model_name='attendanceuploads',
            name='subject_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsite.addsubject', to_field='subject_name'),
        ),
    ]
