# Generated by Django 3.1 on 2020-08-30 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0007_auto_20200826_1504'),
        ('teachers', '0002_auto_20200830_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceuploads',
            name='class_number',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='adminsite.addclassnumber', to_field='class_number'),
        ),
    ]
