# Generated by Django 3.1 on 2020-08-30 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0007_auto_20200826_1504'),
        ('teachers', '0003_attendanceuploads_class_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceuploads',
            name='class_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsite.addclassnumber', to_field='class_number'),
        ),
    ]
