# Generated by Django 3.1 on 2020-08-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_auto_20200830_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultupload',
            name='pass_status',
            field=models.BooleanField(default=False),
        ),
    ]
