# Generated by Django 3.1 on 2020-08-30 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0010_auto_20200830_1326'),
        ('teachers', '0005_resultupload_pass_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultupload',
            name='subject_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsite.addsubject', to_field='subject_name'),
        ),
    ]
