# Generated by Django 3.1 on 2020-08-30 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0010_auto_20200830_1326'),
        ('teachers', '0007_resultupload_class_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultupload',
            name='class_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsite.addclassnumber', to_field='class_number'),
        ),
    ]
